#!/bin/bash
pkg=autoconf
ver="${ver:-2.69}"
rel=1
grp=base
dep=(curl)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L --cacert $SPM_PREFIX/ssl/cert.pem http://ftp.vim.org/ftp/gnu/${pkg}/${pkg}-${ver}.tar.gz
    tar xzf $pkg-${ver}.tar.gz
    cd ${pkg}-${ver}
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig ./configure --silent --prefix=$SPM_PREFIX
    make -s install
}

_list() {
    hash -r
    echo ">> ${pkg} version"
    ${pkg} --version
}
