#!/bin/bash
pkg=automake
ver="${ver:-1.15}"
rel=1
grp=base
dep=(curl autoconf)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L --cacert $SPM_PREFIX/ssl/cert.pem http://ftp.gnu.org/gnu/automake//${pkg}-${ver}.tar.gz
    tar xzf $pkg-${ver}.tar.gz
    cd ${pkg}-${ver}
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig ./configure --silent --prefix=$SPM_PREFIX
    make -s install
}

_list() {
    hash -r
    echo ">> automake version"
    automake --version
}
