#!/bin/bash
pkg=boost
ver="${ver:-1_69_0}"
rel=1
grp=base
dep=(libtool)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://dl.bintray.com/boostorg/release/${ver//_/.}/source/boost_${ver}.tar.bz2
    tar xf ${pkg}_${ver}.tar.bz2
    cd ${pkg}_${ver}
    #./configure --silent --prefix=$SPM_PREFIX --enable-shared
    ./bootstrap.sh --prefix=$SPM_PREFIX
    ./b2 stage threading=multi link=static --with-thread --with-system --with-date_time --with-chrono
    ./b2 install threading=multi link=static --with-thread --with-system --with-date_time --with-chrono
    #make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    #libtoolize  --version
}
