#!/bin/bash
pkg=curl
ver="${ver:-7.64.0}"
rel=1
grp=base
dep=(openssl zlib libidn ca-bundle nghttp2)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl --insecure -O -L --cacert $PREFIX/ssl/cert.pem https://curl.haxx.se/download/curl-${ver}.tar.gz
    tar xzf $pkg-${ver}.tar.gz
    cd ${pkg}-${ver}
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig \
        ./configure --prefix=$PREFIX --with-ca-bundle=$PREFIX/ssl/cert.pem --with-ssl --with-zlib --with-libidn2 --with-nghttp2
    make -s install
}

_list() {
    hash -r
    echo ">> cURL version"
    curl --version
}
