#!/bin/bash
pkg=daemon
ver="${ver:-0.6.4}"
rel=1
grp=base
dep=()
src=(http://libslack.org/daemon/download/${pkg}-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -L -O ${src}
    tar xf $( basename ${src} )
    cd $pkg-${ver}
    make
    make install-daemon SPM_PREFIX=$SPM_PREFIX
}

_list() {
    hash -r
    echo ">> $pkg version"
    $pkg --version
}
