#!/bin/bash
pkg=gettext
ver="${ver:-0.19.7}"
rel=1
grp=base
dep=(ncurses)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://ftp.gnu.org/gnu/${pkg}/${pkg}-${ver}.tar.xz
    tar xf ${pkg}-${ver}.tar.xz
    cd ${pkg}-${ver}
    export CFLAGS="$CFLAGS -fPIC"
    export CXXFLAGS="$CXXFLAGS -fPIC"
    export LDFLAGS="$LDFLAGS -fPIC"
    ./configure --silent --prefix=$SPM_PREFIX --enable-shared
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    $pkg  --version
}
