#!/bin/bash
pkg=gnutls
ver="${ver:-3.6.5}"
rel=1
grp=base
dep=(zlib nettle)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/${pkg}-${ver}.tar.xz
    tar xf ${pkg}-${ver}.tar.xz
    cd ${pkg}-${ver}
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig  ./configure --silent --prefix=$SPM_PREFIX --enable-shared --libdir=$SPM_PREFIX/lib --with-included-libtasn1 --without-p11-kit --with-included-unistring
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion $pkg
}
