#!/bin/bash
pkg=golang14
ver="${ver:-1.4-bootstrap-20171003}"
rel=1
grp=base
dep=()
src=(https://github.com/stedolan/jq/releases/download/jq-${ver}/jq-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    # https://go.dev/doc/install/source
    curl -L -O https://dl.google.com/go/go${ver}.tar.gz
    tar xzf go${ver}.tar.gz
    mv -v go $SPM_PREFIX/go${ver}
    cd $SPM_PREFIX/go${ver}/src

    export CGO_ENABLED=1
    #mkdir -p $GOPATH
    #mkdir -p $GOROOT
    ./make.bash
}

_list() {
    hash -r
    echo ">> $pkg version"
    export GOROOT=$SPM_PREFIX/go${ver}
    $SPM_PREFIX/go${ver}/bin/go version
}
