#!/bin/bash
pkg=golang119
ver="${ver:-1.19.5}"
rel=1
grp=base
dep=(golang14)
src=(https://github.com/stedolan/jq/releases/download/jq-${ver}/jq-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -L -O https://dl.google.com/go/go${ver}.src.tar.gz
    tar xzf go${ver}.src.tar.gz
    mv -v go goroot
    mv -v goroot $SPM_PREFIX/
    cd $SPM_PREFIX/goroot/src

    GOROOT_BOOTSTRAP=$SPM_PREFIX/go1.4.3 ./make.bash
}

_list() {
    hash -r
    echo ">> $pkg version"
    $SPM_PREFIX/goroot/bin/go version
}
