#!/bin/bash
pkg=lftp
ver="${ver:-master}"
rel=1
grp=base
dep=(automake readline ncurses gperf openssl bison)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    set -e
    curl -O -L https://github.com/lavv17/lftp/archive/master.tar.gz
    tar xf master.tar.gz
    cd ${pkg}-${ver}
    #./autogen.sh
    ACLOCAL_FLAGS="-I /usr/share/aclocal/" \
        LIBS="-lreadline -lncurses" \
        PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig \
        ./autogen.sh --prefix=$PREFIX --with-readline=$PREFIX \
       --with-readline-lib=$PREFIX/lib --with-openssl=$PREFIX/lib --without-gnutls --disable-nls
   make -s install
    set +e
}

_list() {
    hash -r
    echo ">> $pkg version"
    lftp --version
}
