#!/bin/bash
pkg=libattr
ver="${ver:-2.4.47}"
rel=1
grp=base
dep=(gettext)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    # their site has broken cert chain
    curl -O -L -k http://download.savannah.nongnu.org/releases/${pkg#lib}/${pkg#lib}-${ver}.src.tar.gz
    tar xf ${pkg#lib}-${ver}.src.tar.gz
    cd ${pkg#lib}-${ver}

    rm $SPM_PREFIX/lib/libattr.so.1
    make configure
    ./configure --prefix=$SPM_PREFIX
    make
    make install install-lib  install-dev
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion $pkg
}
