#!/bin/bash
pkg=libevent
ver="${ver:-2.0.22-stable}"
rel=1
grp=base
dep=()
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://github.com/libevent/libevent/releases/download/release-${ver}/libevent-${ver}.tar.gz
    tar xzf ${pkg}-${ver}.tar.gz
    cd ${pkg}-${ver}
    ./configure --silent --prefix=$PREFIX --enable-shared
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --modversion $pkg
}
