#!/bin/bash
pkg=libffi
ver="${ver:-3.3}"
rel=1
grp=base
dep=(autoconf automake libtool)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://github.com/libffi/libffi/archive/v${ver}.tar.gz
    tar xf v${ver}.tar.gz
    cd ${pkg}-${ver}

    export ACLOCAL_PATH="/home/test/local/share/aclocal/"
    export ACLOCAL_FLAGS="-I /home/test/local/share/aclocal/"

    libtoolize -i -c --quiet
    aclocal --verbose
    ./autogen.sh --prefix=$SPM_PREFIX

    ./configure --silent --prefix=$SPM_PREFIX --libdir=$SPM_PREFIX/lib --disable-multi-os-directory --disable-docs
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    #strings $SPM_PREFIX/lib/libffi.la|grep -e current -e age -e revision
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion ${pkg}
}
