#!/bin/bash
pkg=libidn2
ver="${ver:-2.0.5}"
rel=1
grp=base
dep=()
src=(http://ftp.vim.org/ftp/gnu/libidn/${pkg}-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O http://ftp.vim.org/ftp/gnu/libidn/${pkg}-${ver}.tar.gz
    tar xzf libidn2-${ver}.tar.gz
    cd libidn2-${ver}
    ./configure --silent --prefix=$SPM_PREFIX --enable-shared
    make -s install
}

_list() {
    hash -r
    echo ">> libidn version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion libidn2
}
