#!/bin/bash
pkg=librsync0
ver="${ver:-0.9.7}"
rel=1
grp=base
dep=()
src=(http://ftp.vim.org/ftp/gnu/libidn/${pkg}-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://sourceforge.net/projects/librsync/files/librsync/0.9.7/librsync-0.9.7.tar.gz
    tar xzf librsync-${ver}.tar.gz
    cd librsync-${ver}
    ./configure --silent --prefix=$PREFIX --enable-shared
    make -s install
}

_list() {
    hash -r
    echo ">> librsync version"
    strings $PREFIX/lib/librsync.so |tail -n1
}
