#!/bin/bash
pkg=libssh
ver="${ver:-0.7.3}"
rel=1
grp=base
dep=(cmake)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://red.libssh.org/attachments/download/195/${pkg}-${ver}.tar.xz
    tar xf ${pkg}-${ver}.tar.xz
    #cd ${pkg}-${ver}
    mkdir _build
    cd  _build
    cmake ../${pkg}-${ver} -DCMAKE_INSTALL_SPM_PREFIX:PATH=$SPM_PREFIX
    #./configure --silent --prefix=$SPM_PREFIX --enable-shared
    make -s all install
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion $pkg
}
