#!/bin/bash
pkg=msgpack
ver="${ver:-1.4.1}"
rel=1
grp=base
dep=()
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L https://github.com/msgpack/msgpack-c/releases/download/cpp-1.4.1/${pkg}-${ver}.tar.gz
    tar xzf ${pkg}-${ver}.tar.gz
    cd ${pkg}-${ver}
    ./configure --silent --prefix=$SPM_PREFIX --enable-shared
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion $pkg
}
