#!/bin/bash
pkg=ncurses
ver="${ver:-6.5}"
rel=1
grp=base
dep=()
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O http://ftp.gnu.org/gnu/ncurses/ncurses-${ver}.tar.gz
    tar xzf ${pkg}-${ver}.tar.gz
    cd ${pkg}-${ver}

    export CFLAGS="$CFLAGS -fPIC"
    export CXXFLAGS="$CXXFLAGS -fPIC"
    export LDFLAGS="$LDFLAGS -fPIC"

    ./configure --silent --prefix=$SPM_PREFIX --enable-shared
    make -s
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    ncurses6-config --version
}
