#!/bin/bash
pkg=nettle
ver="${ver:-3.4.1}"
rel=1
grp=base
dep=(gmp gcc)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L http://ftp.gnu.org/gnu/nettle/${pkg}-${ver}.tar.gz
    tar xzf ${pkg}-${ver}.tar.gz
    cd ${pkg}-${ver}
    ./configure --silent --prefix=$SPM_PREFIX --enable-shared --libdir=$SPM_PREFIX/lib
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion $pkg
}
