#!/bin/bash
pkg=nghttp2
ver="${ver:-1.35.1}"
rel=1
grp=base
dep=()
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L  https://github.com/nghttp2/nghttp2/releases/download/v1.35.1/nghttp2-${ver}.tar.gz
    tar xf ${pkg}-${ver}.tar.gz
    cd ${pkg}-${ver}

    #PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig \
    #ACLOCAL_FLAGS="-I /usr/share/aclocal/" \
    #    LIBS="-lreadline -lncurses" \
    #    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig \
    ./configure --silent --prefix=$SPM_PREFIX --enable-python-bindings=no
    make -s install
}

_list() {
    hash -r
    echo ">> $pkg version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion libnghttp2
}
