#!/bin/bash
pkg=node
ver="${ver:-v10.14.2}"
rel=1
grp=base
dep=(openssl zlib ca-bundle gcc)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl --insecure -O -L --cacert $SPM_PREFIX/ssl/cert.pem https://nodejs.org/dist/${ver}/${pkg}-${ver}.tar.gz
    tar xzf $pkg-${ver}.tar.gz
    cd ${pkg}-${ver}
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig \
        ./configure --prefix=$SPM_PREFIX   \
        --shared-openssl-libpath=$SPM_PREFIX/lib --shared-openssl-includes=$SPM_PREFIX/include/ --shared-openssl \
        --shared-zlib-libpath=$SPM_PREFIX/lib --shared-zlib-includes=$SPM_PREFIX/include/ --shared-zlib
    make -s install
}

_list() {
    hash -r
    echo ">> ${pkg} version"
    ${pkg} --version
}
