#!/bin/bash
pkg=node-bin
ver="${ver:-v8.14.1}"
rel=1
grp=base
dep=(ca-bundle)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    case `arch` in 
        x86_64) url=https://nodejs.org/dist/${ver}/node-${ver}-linux-x64.tar.gz ;;
        i?86)   url=https://nodejs.org/dist/${ver}/node-${ver}-linux-x86.tar.gz ;;
    esac

    curl --insecure -O -L --cacert $SPM_PREFIX/ssl/cert.pem $url
    tar xf $( basename $url )
    mv node-${ver}-linux-*/ node/
    rm -rf $SPM_PREFIX/node
    mv node/ $SPM_PREFIX/
}

_list() {
    hash -r
    echo ">> ${pkg} version"
    node --version
}
