#!/bin/bash
pkg=openssl
ver="${ver:-1.0.2h}"
rel=1
grp=base
dep=()
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    unset MAKEFLAGS
    curl -O -L ftp://ftp.openssl.org/source/openssl-${ver}.tar.gz
    tar xzf openssl-${ver}.tar.gz
    cd openssl-${ver}
    ./config --prefix=$PREFIX shared
    make -s install
}

_list() {
    hash -r
    echo ">> OpenSSL version"
    openssl version
}
