#!/bin/bash
pkg=openssl
ver="${ver:-1.1.1d}"
rel=1
grp=base
dep=(zlib)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    unset MAKEFLAGS
    curl -O -L https://www.openssl.org/source/openssl-${ver}.tar.gz
    tar xzf openssl-${ver}.tar.gz
    cd openssl-${ver}
    ./config no-sse2 enable-camellia \
        enable-ec enable-idea enable-mdc2 \
        enable-rc5 enable-asm \
        no-rfc3779 no-sctp \
        no-ssl2 no-ssl3 enable-heartbeats \
        enable-zlib --prefix=$SPM_PREFIX shared threads  -I${SPM_PREFIX}/include -L$SPM_PREFIX/lib
    #-I${_bootstrap}/usr/include -I${SPM_PREFIX}/include -L${_bootstrap}/usr/lib64 -L$SPM_PREFIX/lib
    make
    make -s install_sw
}

_list() {
    hash -r
    echo ">> OpenSSL version"
    openssl version
}
