#!/bin/bash
pkg=pip
ver="${ver:-current}"
rel=1
grp=base
dep=(python2)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    #curl -O https://bootstrap.pypa.io/get-pip.py 
    #python2 get-pip.py
    python -m ensurepip --default-pip
}

_list() {
    hash -r
    echo ">>> PiP version"
    pip --version
}
