#!/bin/bash
pkg=python2
ver="${ver:-2.7.13}"
rel=1
grp=base
dep=(openssl zlib curl)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O https://www.python.org/ftp/python/$ver/Python-$ver.tgz
    tar xzf Python-$ver.tgz
    cd Python-$ver
    PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig ./configure --silent --prefix=$PREFIX --enable-shared
    make -s install
}

_list() {
    hash -r
    echo ">>Python2 version"
    echo "$( $pkg --version 2>&1 | tr -d '\n\r' ) / $( $pkg -c "import ssl;print ssl.OPENSSL_VERSION;print ssl.get_default_verify_paths()" )"
}
