#!/bin/bash
pkg=rdiffweb
ver="${ver:-git}"
rel=1
grp=base
dep=(babel jinja2 cherrypy pysqlite)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L  https://github.com/ikus060/rdiffweb/archive/master.tar.gz
    tar xzf master.tar.gz
    cd rdiffweb-master
    python setup.py install --prefix $PREFIX
    mkdir -vp $PREFIX/etc/rdiffweb
    cp -v rdw.conf $PREFIX/etc/rdiffweb
}

_list() {
    hash -r
    echo ">> $pkg version"
    echo ">>>> $pkg: $( cat $( which rdiffweb )|grep EASY-INSTALL-ENTRY-SCRIPT|awk -F "'" '{print $2}' )"
}
