#!/bin/bash
pkg=redis
ver="${ver:-3.2.0}"
rel=1
grp=base
dep=()
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O -L http://download.redis.io/releases/${pkg}-${ver}.tar.gz
    tar xzf $pkg-${ver}.tar.gz
    cd ${pkg}-${ver}
    make -s PREFIX=$PREFIX install
}

_list() {
    hash -r
    echo ">> redis-server version"
    redis-server --version
}
