#!/bin/bash
pkg=sqlalchemy
ver="${ver:-3090000}"
rel=1
grp=base
dep=(pip sqlite3)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    pip install sqlalchemy
}

_list() {
    hash -r
    echo ">> ${pkg} version"
    echo ">>>> sqlalchemy: $( pip show sqlalchemy|grep ^Version )"
}
