#!/bin/bash
pkg=sqlite3
ver="${ver:-3090000}"
rel=1
grp=base
dep=(curl)
src=(http://ftp.gnu.org/gnu/libidn/libidn-${ver}.tar.gz)
sha=(ca91d22f017bfcb503d4bc3b44295491c89a33a3df0c3d8b8614f2d3831836eb)

_build() {
    curl -O https://www.sqlite.org/2015/sqlite-autoconf-${ver}.tar.gz
    tar xzf sqlite-autoconf-${ver}.tar.gz
    cd sqlite-autoconf-${ver}
    ./configure --silent --prefix=$SPM_PREFIX
    make -s install
}

_list() {
    hash -r
    echo ">> ${pkg} version"
    PKG_CONFIG_PATH=$SPM_PREFIX/lib/pkgconfig pkg-config --modversion sqlite3
}
