language: cpp

jobs:
    include:
        - stage: "Start with openssl"
          name: "openssl"
          script: ./spm install openssl
        - stage: "Now build rest"
          name: "notary"
          script: ./spm install notary
#        - script: ./spm install ocserv
#          name: "ocserv"
        - script: ./spm install rdiff-backup
          name: "rdiff-backup"
