language: cpp

jobs:
    include:
        - stage: openssl
          script: ./spm install openssl
        - stage: notary
          script: ./spm install notary
        - stage: ocserv
          script: ./spm install ocserv
        - stage: rdiff-backup
          script: ./spm install rdiff-backup
