language: cpp

jobs:
    include:
        - stage: "test spm builds"
          name: "openssl"
          script: ./spm install openssl
        - script: ./spm install notary
          name: "notary"
        - script: ./spm install ocserv
          name: "ocserv"
        - script: ./spm install rdiff-backup
          name: "rdiff-backup"
