jobs:
    test_python:
        runs-on: ubuntu-latest
        steps:
            - run: ./spm install openssl
            - run: ./spm install python3
    test_notary:
        runs-on: ubuntu-latest
        steps:
            - run: ./spm install notary
