name: Test Builds
on:
    push:
    workflow_dispatch:
    schedule:
        - cron:  '27 15 * * 3'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ./spm install openssl
            - run: ./spm install curl
            - run: ./spm install python3
            - run: ./spm install git
            - run: ./spm install golang122
